### PR TITLE
Feature/color adjustments 2

### PR DESCRIPTION
**Pull request by michac789**
This is based on this closed PR: https://github.com/glints-dev/glints-aries/pull/820
The old PR was closed because the commits were messy, and there were some snapshot (testing) issues.

Note:

I didn't expect these 2 files to change, but for some reason, it changed:
- `test/e2e/badge/badge.spec.ts-snapshots/badge-information-chromium-linux.png`
- `test/e2e/badge/badge.spec.ts-snapshots/badge-information-small-chromium-linux.png`

### CODE REVIEW

**Comment by ninariccimarie** [comment]
hmm it seems we missed to update the args [here](https://github.com/glints-dev/glints-aries/blame/v4/test/e2e/badge/badge.spec.ts#L18) and [here](https://github.com/glints-dev/glints-aries/blame/v4/test/e2e/badge/badge.spec.ts#L68) previously which should be `'args=status:information'` instead. can you help to update both these tests? and it should use the blue bg. You can verify what we should expect on the component based on the Figma of Design System. If you see it's wrong, either we broke it or the Figma is not up to date.

on a separate issue, we should investigate why the test didn't fail previously. 😞

**Comment by michac789** [comment]
> hmm it seems we missed to update the args [here](https://github.com/glints-dev/glints-aries/blame/v4/test/e2e/badge/badge.spec.ts#L18) and [here](https://github.com/glints-dev/glints-aries/blame/v4/test/e2e/badge/badge.spec.ts#L68) previously which should be `'args=status:information'` instead. can you help to update both these tests? and it should use the blue bg. You can verify what we should expect on the component based on the Figma of Design System. If you see it's wrong, either we broke it or the Figma is not up to date.
> 
> on a separate issue, we should investigate why the test didn't fail previously. 😞

sure let me check! and yeah the CI is not working as expected :(
when I'm free perhaps I can try experimenting with the CI 

Edit: I'm done making those changes, checked the Figma, yeah it should be blue color, the wrong args made it wrong

**Review by ninariccimarie — APPROVED** [review]
LGTM 👍 thanks!

**Review by chiahou — APPROVED** [review]
qc passed.

**Pull request merged**
