### PR TITLE
Modal: Restore previous media queries (Recreated PR)

### PR DESCRIPTION
**Pull request by westwood846**
This fixes a regression where the modal didn't have the correct width
because the definitions of our device classes changed.

### CODE REVIEW

**Comment by tingtingdisco** [comment]
@westwood846 I checked that `Device` has been used by ModalStyle, AlertStyle, SearchFilterStyle and GlintsContaner, do we also need to update them?

**Comment by westwood846** [comment]
> @westwood846 I checked that `Device` has been used by ModalStyle, AlertStyle, SearchFilterStyle and GlintsContaner, do we also need to update them?

Hmm you're right, there is one reference in `AlertStyle` and three in `SearchFilterStyle` which need to be updated. Modal is updated now and GlintsContainer has been updated in the original PR.

**Comment by tingtingdisco** [comment]
LGTM thank u @westwood846

**Review by tingtingdisco — APPROVED** [review]
LGTM

**Pull request merged**
