### PR TITLE
fix: set loading to be false if no file provided

### PR DESCRIPTION
**Pull request by ganiirsyadi**

### CODE REVIEW

**Review by michac789 — CHANGES_REQUESTED** [review]
Can you change the line that you added to:
```
else if (!loading) setIsLoading(false);
```
If loading=true is given (tbh don't think this is even being used lol), you will always see the loading spinner. Your logic makes it so that even if loading=true, the loading state will be set to false there. And that's the reason that a test case is failing.

Another alternative is actually remove the loading prop entirely (if no one uses it) and remove the corresponding test case there.

**Comment by ganiirsyadi** [comment]
> Can you change the line that you added to:
> 
> ```
> else if (!loading) setIsLoading(false);
> ```
> 
> If loading=true is given (tbh don't think this is even being used lol), you will always see the loading spinner. Your logic makes it so that even if loading=true, the loading state will be set to false there. And that's the reason that a test case is failing.
> 
> Another alternative is actually to remove the loading prop entirely (if no one uses it) and remove the corresponding test case there.

If I added that line, then my problem will still exist, since the `loading` value is `true` in my case. Steps: I upload the SVG image, based on my validation it's failing, hence the `file` props I passed to the Upload component will be null. Though, the loading is already set to `true` due to `handleChange` function that was triggered.

**Comment by finalight** [comment]
can see there's a snapshot test failure, would need that to be updated somehow

**Review by michac789 — APPROVED** [review]
lgtm! 

note: can consider removing the loading prop entirely in the future if it is useless

**Comment by ganiirsyadi** [comment]
> lgtm!
> 
> note: can consider removing the loading prop entirely in the future if it is useless

And supporting `imageUrl`

**Comment by finalight** [comment]
is this okay?

image

**Comment by ganiirsyadi** [comment]
> is this okay?
> 
> image

Fixed

**Pull request merged**
