### PR TITLE
Popover: Add a property to show the number of options selected as a badge

### PR DESCRIPTION
**Pull request by ritikamotwani**
Fixes: #166 
Add a property to the pop over called showBadgeNumber which if greater than 0 shows a badge with the number specified.

### CODE REVIEW

**Comment by franciscrispin** [comment]
Hi @ritikamotwani ,

@aaa59891 and I had some discussions about this.

They key question is whether this behaviour to show the badge should belong in aries or should be customized by the developer in the codebase.

To help us think about it, we categorized components into 3 groups. (Note `codebase` here refers to `dst`/`employers`)
1. cross-project component - should exist in glints-aries
2. global shared component - should exist in the shared components folder in the codebase 
3. feature component - should exists in the module in the codebase

I'm not sure whether this behaviour is required in `employers`. If it is, we can add it in aries. If it isn't, then this should be done on `dst` itself by extending the aries `Popover` component.

**Comment by ritikamotwani** [comment]
@franciscrispin I guess then this behaviour shouldn't be added in aries.
The reason being a Popover component in any of the public UI libraries rarely has this badge thing. This can be included in the shared component of the `dst` repo, as it would make more sense there, and as the filter being used in `dst` is similar everywhere, if some dev finds more things to be changed for the Popover to reused as a filter, they can simply refactor the shared component so that it's similar in the project.

**Comment by franciscrispin** [comment]
@ritikamotwani Yeap agree with your assessment! Feel free to close the issue if there are no more issues :smile:

**Comment by ritikamotwani** [comment]
Closing the PR and issue in respect to the discussion here: https://github.com/glints-dev/glints-aries/pull/167#issuecomment-564005868

**Pull request closed without merging**
