### PR TITLE
DataTable: fix horizontal scroll

### PR DESCRIPTION
**Pull request by ninariccimarie**
| BEFORE | AFTER |
|--------|--------|
| Kapture 2023-03-16 at 17 27 19 | Kapture 2023-03-16 at 17 28 12 |

### CODE REVIEW

**Comment by marthayaputra** [comment]
@ninariccimarie, now the table cell content won't wrap if it's long, I remember last time we only want the header to not wrap, has this changed @chiahou

**Review by chiahou — APPROVED** [review]
qc passed, thanks!

**Review by marthayaputra — APPROVED** [review]
LGTM

**Review by chiahou — APPROVED** [review]
all good

**Pull request merged**
