### PR TITLE
disable typing Select shouldn't have cursor and open mobile keyboard

### PR DESCRIPTION
**Pull request by rosslo**
Related issue: https://github.com/glints-dev/glints-aries/issues/222

### CODE REVIEW

**Comment by westwood846** [comment]
Can you please remove the `yarn.lock` commit? Just delete it with interactive rebase and force-push to this branch.

**Comment by rosslo** [comment]
> Can you please remove the `yarn.lock` commit? Just delete it with interactive rebase and force-push to this branch. IMO `yarn.lock` updates should only go with dependency changes or deliberate dependency upgrades.

**Comment by rosslo** [comment]
@westwood846 Yeah, agree with your point to yarn.lock updates. But I think it's okay to update `yarn.lock` within this MR, those updates of it related to https://github.com/glints-dev/glints-aries/pull/182/files. Which the dev forgot to update `yarn.lock`.

**Comment by westwood846** [comment]
> Or do you think we should have another for it?

Usually I would prefer another MR but I don't see the point of being so pedantic here. Should be fine :D

**Comment by westwood846** [comment]
LGTM

**Pull request merged**
