### PR TITLE
Tooltip: change font to subtitle2, update snapshots

### PR DESCRIPTION
**Pull request by michac789**

### CODE REVIEW

**Review by chiahou — APPROVED** [review]
looks good to me, thanks!

**Review by ninariccimarie — CHANGES_REQUESTED** [review]
there are unrelated files in the changes. specifically the `TextArea` directory. 
do rebase as well

**Comment by michac789** [comment]
> there are unrelated files in the changes. specifically the `TextArea` directory. do rebase as well



> there are unrelated files in the changes. specifically the `TextArea` directory. do rebase as well

fixed by rebasing, not sure why is that so... the commit wasn't done by me I think it's some issue related to GitHub hmm... now should be good

**Review by ninariccimarie — APPROVED** [review]
LGTM

**Pull request merged**
