### PR TITLE
Utils: @next foundation colors

### PR DESCRIPTION
**Pull request by ninariccimarie**
https://glints.atlassian.net/browse/SS-721

## Figma
[Branding Color](https://www.figma.com/file/J4wDmLPXT3BChWIasEWpUu/Glints-Design-System?node-id=3938%3A31072&t=My6NMmxkmtuy8mpb-4)
[Product Color](https://www.figma.com/file/J4wDmLPXT3BChWIasEWpUu/Glints-Design-System?node-id=3925%3A30153&t=My6NMmxkmtuy8mpb-4)

## Storybook update
Screenshot 2022-12-01 at 5 05 42 PM

## Nested Tree Shaking Evidence
https://glints.atlassian.net/browse/SS-721?focusedCommentId=22479

### CODE REVIEW

**Comment by marthayaputra** [comment]
@ninariccimarie , I think it's better to separate each named color to its own const for a better tree-shaking, like if my app only need 1 or 2 blue variants, I don't have to import all blue variant.

**Comment by ninariccimarie** [comment]
thanks @marthayaputra I've improved the tree shaking by following this: https://github.com/webpack/changelog-v5/blob/master/README.md#nested-tree-shaking we should note that this is only compatible with webpack 5 so we must upgrade other FE services that aren't in v5 yet

**Comment by marthayaputra** [comment]
> thanks @marthayaputra I've improved the tree shaking by following this: https://github.com/webpack/changelog-v5/blob/master/README.md#nested-tree-shaking we should note that this is only compatible with webpack 5 so we must upgrade other FE services that aren't in v5 yet

Oh nice work!

**Review by marthayaputra — APPROVED** [review]
LGTM

**Pull request merged**
