### PR TITLE
Feat: Fix truncation and add ellipsis

### PR DESCRIPTION
**Pull request by farhanabi**
Truncating words when it overflows in the select component

image
image

### CODE REVIEW

**Review by marthayaputra — COMMENTED** [review]
@farhanabi can we add tests for those changes?

**Comment by farhanabi** [comment]
> @farhanabi can we add tests for those changes?

Added the test cases @marthayaputra 🙏

**Review by marthayaputra — APPROVED** [review]
LGTM

**Review by chiahou — COMMENTED** [review]
@farhanabi it seems that the horizontal scrollbar inside the option menu is breaking the select component 
image
image

Can we go with this approach instead? https://www.figma.com/file/87fhOdF8vk1Uiy20bCqS85/Sirius-Web---UI-Kit-3.0-%5BQ4-2022%5D?type=design&node-id=6770-55509&mode=design&t=0jhMfjd31ccvTZx2-4

**Review by chiahou — APPROVED** [review]
looks good to me, thanks!

**Pull request merged**
