### PR TITLE
Select: drop button should not be rendered when select is disabled

### PR DESCRIPTION
**Pull request by tingtingdisco**
https://user-images.githubusercontent.com/11376798/105022504-d1faf580-5a84-11eb-9650-f1447a81ff8c.mov

### CODE REVIEW

**Comment by rosslo** [comment]
Just checked the other UI libraries, they don't hide the drop button when select is disabled.

- Material-UI: https://material-ui.com/components/selects/#select
image
- Ant Design: https://ant.design/components/select/
image


Do you think we can do `onClick={disabled ? undefined : handleDropIconClick}` instead?

**Comment by rosslo** [comment]
Btw, do you think we should remove the hover state for disabled select together? 🙏

**Comment by tingtingdisco** [comment]
> Btw, do you think we should remove the hover state for disabled select together? 🙏
hmm, we should ask designers.

**Comment by tingtingdisco** [comment]
but I think we can follow other libraries first.

**Comment by tingtingdisco** [comment]
@rosslo updated, thank u

**Review by rosslo — APPROVED** [review]

**Comment by rosslo** [comment]
@tingtingdisco , LGTM, thanks for the fix.

**Comment by tingtingdisco** [comment]
@rosslo what's the UI Tests task?

**Comment by rosslo** [comment]
@tingtingdisco , the snapshot check for storybook, the reviewer should also review it and approve the change on chromatic. I thought I have approved it. 😅 

Btw, the change is the glints-aries version in the homepage.
image

**Pull request merged**
