### PR TITLE
DataTable typography and icons updates

### PR DESCRIPTION
**Pull request by ninariccimarie**

### CODE REVIEW

**Review by chiahou — COMMENTED** [review]
@ninariccimarie it appears that there is excessive empty space considering the smaller font size we are currently using. I wonder if the spacing should be defined here or not? Can it be customized at a product level?

**Comment by ninariccimarie** [comment]
@chiahou If it would make more sense to redefine the spacing as well, then we can redefine from here cause it would be troublesome to redefine spacing from the product side every time we use DataTable

**Comment by chiahou** [comment]
@ninariccimarie I see. Then can we adjust the paddings of each cell from `16px` to `8px 16px`. And one more thing, can we remove the `vertical align: top` or maybe we can expose this attribute

**Review by chiahou — APPROVED** [review]
lgtm, thx!

**Review by michac789 — APPROVED** [review]
lgtm

**Pull request merged**
